fix: Migrate to `slim` base image
Problem:
Runtime errors from missing GNU libraries torch (transformers) requires

Error:
```
OSError: Error relocating /usr/local/lib/python3.12/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found`.
```

Fix:
Migrate to `slim-bullseye` to resolve underlying C library versions.

[Note]
Patch `RUN` layer due to `make` utility not installed in container.