Patch & upgrade docker image (#1)
* refactor: Return json response

Update `home` endpoint to serialize the given arguments and return JSON.

[Reason]
Prefer serialized JSON to avoid errors from output parser tools (`jq`).

* docs: Patch and update readme

Patches made:
- Update HTTP method to server requirement, `POST`.
- Update CURL request to pass `data` and not `query_param` text input.
- Update the reference `shell` to `bash` for commands to execute.
- Fix typos and spelling errors.

* chore: Add type hints

Annotate code with type hints.
Add custom types for complex native data structures.

[Reason]
Improve readability and code documentation with type inference.

[Note]
Loggers were temporary set to analyze data in program flow.
```
app.logger.setLevel(logging.DEBUG)
app.logger.addHandler(logging.StreamHandler())
```

* build: Patch layers and upgrade `py` version

Migrate to use alpine flavor for base image.
Upgrade base image tag to tested version: `py312`.
Add patches to Dockerfile for successful image build:
- Remove redundant layer to copy `Makefile`.
- Set layers in correct order

[Note]
Due to anomalies during image build,
the above patches were required.

* fix: Migrate to `slim` base image

Problem:
Runtime errors from missing GNU libraries torch (transformers) requires

Error:
```
OSError: Error relocating /usr/local/lib/python3.12/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found`.
```

Fix:
Migrate to `slim-bullseye` to resolve underlying C library versions.

[Note]
Patch `RUN` layer due to `make` utility not installed in container.

* perf: Optimize image recipe

Optimize and improve `Dockerfile` with the following patches:
- Add `ENVs` to configure container behavior.
- Add bind-mount and cache for app dependencies.
- Add clear doc comments for first-time users.

[Note]
- The patch to add a `non-root user` addresses security not performance.
- Give `appuser` ownership to support deps needing write permissions
  (ie. A dependency that needs to write to a `cache` dir)

* chore: Add ignore file (docker)

Define files/dirs to exclude from COPY container during build.

[Note]
Should be files/dirs not published or deployed in production.

* refactor: Update formatter util

Update utility function to handle correct type by list unpacking.
Update custom type alias for the model's prediction.

[Chore]
- Add trailing commas for better `diff` analysis.
- Prefer double over single quotes.

* docs: Tag image and update command

Follow Docker best practice and prefer to tag images.
Modify `docker run` command to improve readability
Update venv `name` to match entry in `.dockerignore`.

[Note]
Tag `dev` was chosen in sync with the app's runtime in `DEBUG` mode.

* chore: Support reproducible build

Add tested/pinned requirements for users to fall back to
(ie. if unpinned versions introduce BREAKING CHANGES).

[Commands]
# Freeze tested requirements
➜ pip freeze > requirements.txt

[Chore]
- Update README to inform users on installation fall back.
- Prevent copying `.in` requirements into container.